KPMG.Assignment.Web/Models/UploadViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Web;

namespace KPMG.Assignment.Web.Models
{
    public class UploadViewModel
    {
        [DisplayName("Upload a valid transaction file")]
        [Required(ErrorMessage = "Valid transaction file is required!")]
        public HttpPostedFileBase TransactionFile { get; set; }

        public DataTable TransactionTable { get; set; }

        public string FileText { get; set; }
    }
}

KPMG.Assignment.Web/Controllers/AccountTransactionController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using KPMG.Assignment.Web.DAL;
using KPMG.Assignment.Web.Models;

namespace KPMG.Assignment.Web.Controllers
{
    public class AccountTransactionController : Controller
    {
        private readonly UnitOfWork _unitOfWork = new UnitOfWork();

        // GET: AccountTransactions
        public ActionResult Index()
        {
            return View(_unitOfWork.AccountTransactionRepository.Get().ToList());
        }

        // GET: AccountTransactions/Details/5
        public ActionResult Details(int id)
        {
            var accountTransaction = _unitOfWork.AccountTransactionRepository.GetById(id);
            if (accountTransaction == null)
                return HttpNotFound();
            return View(accountTransaction);
        }

        // GET: AccountTransactions/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AccountTransactions/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(
            [Bind(Include = "TransactionId,Account,Description,CurrencyCode,Amount,TransactionDate")] AccountTransaction
                accountTransaction)
        {
            if (ModelState.IsValid)
            {
                accountTransaction.TransactionDate = DateTime.Now;
                accountTransaction.Active = true;

                _unitOfWork.AccountTransactionRepository.Insert(accountTransaction);
                _unitOfWork.Save();

                return RedirectToAction("Index");
            }
            return View(accountTransaction);
        }

        // GET: AccountTransactions/Edit/5
        public ActionResult Edit(int id)
        {
            var accountTransaction = _unitOfWork.AccountTransactionRepository.GetById(id);
            if (accountTransaction == null)
                return HttpNotFound();
            return View(accountTransaction);
        }

        // POST: AccountTransactions/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(
            [Bind(Include = "TransactionId,Account,Description,CurrencyCode,Amount,TransactionDate,Active")] AccountTransaction accountTransaction)
        {
            if (!ModelState.IsValid) return View(accountTransaction);

            accountTransaction.TransactionDate = DateTime.Now;
            _unitOfWork.AccountTransactionRepository.Update(accountTransaction);
            _unitOfWork.Save();

            return RedirectToAction("Index");
        }

        // GET: AccountTransactions/Delete/5
        public ActionResult Delete(int id)
        {
            var accountTransaction = _unitOfWork.AccountTransactionRepository.GetById(id);
            if (accountTransaction == null)
                return HttpNotFound();
            return View(accountTransaction);
        }

        // POST: AccountTransactions/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var accountTransaction = _unitOfWork.AccountTransactionRepository.GetById(id);
            accountTransaction.TransactionDate = DateTime.Now;
            accountTransaction.Active = false;

            _unitOfWork.AccountTransactionRepository.Update(accountTransaction);
            _unitOfWork.Save();

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            _unitOfWork.Dispose();
            base.Dispose(disposing);
        }
    }
}

KPMG.Assignment.Web/Controllers/UploadController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using Excel;
using KPMG.Assignment.Web.DAL;
using KPMG.Assignment.Web.Models;
using KPMG.Assignment.Web.Utilities;
using LumenWorks.Framework.IO.Csv;

namespace KPMG.Assignment.Web.Controllers
{
    public class UploadController : Controller
    {
        private readonly UnitOfWork _unitOfWork = new UnitOfWork();

        public ActionResult Index()
        {
            return View(new UploadViewModel());
        }

        public ActionResult AddFileContent()
        {
            var viewModel = new ContentAddedViewModel();
            var dt = TempData["TransactionTable"] as DataTable;

            return View(dt == null ? viewModel : AddOrUpdateAccountTansaction(dt));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(UploadViewModel uploadViewModel)
        {
            if (ModelState.IsValid)
            {
                if ((uploadViewModel.TransactionFile == null) || (uploadViewModel.TransactionFile.ContentLength <= 0))
                {
                    ModelState.AddModelError("File",
                        "Please upload a valid file. The format must be in Excel (xlsx) or CSV.");
                    return View(uploadViewModel);
                }

                var stream = uploadViewModel.TransactionFile.InputStream;

                if (uploadViewModel.TransactionFile.FileName.EndsWith(".xlsx"))
                {
                    using (var excelDataReader = ExcelReaderFactory.CreateOpenXmlReader(stream))
                    {
                        excelDataReader.IsFirstRowAsColumnNames = true;
                        var resultDataSet = excelDataReader.AsDataSet();
                        uploadViewModel.TransactionTable = resultDataSet.Tables[0];
                    }
                }
                else if (uploadViewModel.TransactionFile.FileName.EndsWith(".csv"))
                {
                    using (var csvReader = new CsvReader(new StreamReader(stream), true))
                    {
                        uploadViewModel.TransactionTable = new DataTable();
                        uploadViewModel.TransactionTable.Load(csvReader);
                    }
                }

                else
                {
                    ModelState.AddModelError("File",
                        "The uploaded file format is not supported. The format must be in Excel (xlsx) or CSV.");

                    return View(uploadViewModel);
                }

                TempData["TransactionTable"] = uploadViewModel.TransactionTable;

                return View(uploadViewModel);
            }

            ModelState.AddModelError("File", "Please upload a valid file. The format must be in Excel (xlsx) or CSV.");
            return View(uploadViewModel);
        }

        private static bool TryValidate(object accountTransaction, out List<ValidationResult> results)
        {
            var context = new ValidationContext(accountTransaction);
            results = new List<ValidationResult>();

            return Validator.TryValidateObject(accountTransaction, context, results);
        }

        private ContentAddedViewModel AddOrUpdateAccountTansaction(DataTable dataTable)
        {
            var contentAddedViewModel = new ContentAddedViewModel();
            var lineNumber = 1;

            contentAddedViewModel.FailedLines = new Dictionary<int, string>();
            contentAddedViewModel.NumberOfLines = dataTable.Rows.Count;

            foreach (DataRow dataRow in dataTable.Rows)
            {
                try
                {
                    var amountText = dataRow["Amount"].ToString();
                    if (AssignmentLibrary.IsValidDecimal(amountText))
                    {
                        var accountTransaction = new AccountTransaction
                        {
                            Account = dataRow["Account"].ToString(),
                            Description = dataRow["Description"].ToString(),
                            CurrencyCode = dataRow["Currency Code"].ToString(),
                            Amount = Convert.ToDecimal(amountText),
                            TransactionDate = DateTime.Now,
                            Active = true
                        };

                        List<ValidationResult> results;

                        if (TryValidate(accountTransaction, out results))
                        {
                            _unitOfWork.AccountTransactionRepository.Insert(accountTransaction);
                            contentAddedViewModel.NumberOfImportedLines++;
                        }
                        else
                        {
                            contentAddedViewModel.FailedLines.Add(lineNumber,
                                string.Join(". ", results.Select(e => e.ErrorMessage)));
                        }
                    }
                    else
                    {
                        contentAddedViewModel.FailedLines.Add(lineNumber,
                            "Valid amount is required - Amount must be a valid number!");
                    }
                }
                catch (Exception ex)
                {
                    contentAddedViewModel.FailedLines.Add(lineNumber, ex.Message);
                }
                lineNumber++;
            }
            try
            {
                _unitOfWork.Save();
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", e.Message);
            }

            return contentAddedViewModel;
        }
    }
}

KPMG.Assignment.Web/Views/Upload/AddFileContent.cshtml
@model KPMG.Assignment.Web.Models.ContentAddedViewModel
@{
    ViewBag.Title = "AddFileContent";
}

<h2>Transaction Import</h2>
<p>
    @Html.ValidationSummary(true, "", new {@class = "text-danger"})
</p>
@if (ViewData.ModelState.IsValid)
{
    var numberOfFailedLines = Model.NumberOfLines - Model.NumberOfImportedLines;
    <h4>Import Details:</h4>
    <table class="table">
        <tr>
            <th>
                Total number of lines
            </th>
            <th>
                Number of lines imported
            </th>
            <th>
                Number of failes lines
            </th>
        </tr>
        <tr>
            <td>
                @Model.NumberOfLines.ToString()
            </td>
            <td>
                @Model.NumberOfImportedLines.ToString()
            </td>
            <td>@numberOfFailedLines.ToString()</td>
        </tr>


    </table>
    if (Model.FailedLines.Count > 0)
    {
        <h4>Failed Lines:</h4>
        <table class="table">
            <tr>
                <th>
                    Line Number
                </th>
                <th>
                    Error Message
                </th>
            </tr>

            @foreach (var item in Model.FailedLines)
            {
                <tr>
                    <td>
                        @item.Key.ToString()
                    </td>
                    <td>
                        @item.Value
                    </td>
                </tr>
            }

        </table>
    }
}

<div>
    @Html.ActionLink("Upload new file", "Index") |
    @Html.ActionLink("View Transaction", "Index", "AccountTransaction")
</div>

KPMG.Assignment.Web/Views/Upload/Index.cshtml
@using System.Data
@model KPMG.Assignment.Web.Models.UploadViewModel

@{
    ViewBag.Title = "Account Transaction - Upload";
}
<br/>
<div class="form-horizontal">
    @if (Model.TransactionTable != null)
         {
             <table id="uploadTransactionTable" class="display" width="100%">
                 <thead>
                 <tr>
                     @foreach (DataColumn dataColumn in Model.TransactionTable.Columns)
                     {
                         <th>@dataColumn.ColumnName</th>
                     }
                 </tr>
                 </thead>
                 <tbody>
                 @foreach (DataRow dataRow in Model.TransactionTable.Rows)
                 {
                     <tr>
                         @foreach (DataColumn columnValue in Model.TransactionTable.Columns)
                         {
                             <td>@dataRow[columnValue.ColumnName]</td>
                         }
                     </tr>
                 }
                 </tbody>
             </table>
             <br/>
             <div>
                 @Html.ActionLink("Upload new file", "Index") |
                 @Html.ActionLink("Save", "AddFileContent")
             </div>
         }
         else
         {
             using (Html.BeginForm("Index", "Upload", FormMethod.Post, new {enctype = "multipart/form-data"}))
             {
                 <h2>Account Transaction Upload - The format must be in Excel (xlsx) or CSV.</h2>
                 <br/>
                 @Html.AntiForgeryToken()

                 @Html.ValidationSummary(true, "", new {@class = "text-danger"})


                 <div class="form-group">
                     @Html.LabelFor(model => model.TransactionFile, new {@class = "control-label col-md-2"})
                     <div class="col-md-10">
                         @Html.TextBoxFor(model => model.TransactionFile, new {type = "file"})
                         @Html.ValidationMessageFor(model => model.TransactionFile, "", new {@class = "text-danger"})
                     </div>
                 </div>

                 <div class="form-group">
                     <div class="col-md-offset-2 col-md-10">
                         <input type="submit" value="Upload" class="btn btn-default"/>
                     </div>
                 </div>
             }
         }
</div>

@section scripts {
    <script type="text/javascript">
                    $(document)
                        .ready(function () {
                            $('#uploadTransactionTable').DataTable({
                                "paging": false,
                                "ordering": false,
                                "searching": false,
                                "info": false
                            });
                        });
    </script>
}